// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// gwpca_cpp
List gwpca_cpp(const arma::mat& data, const arma::mat& coords, double bandwidth, std::string method, bool use_correlation, int k, bool detect_outliers, double outlier_threshold, double trim_prop, double h_fraction, int lof_k, double bacon_alpha, std::string depth_type, int robpca_k_max, bool parallel, int n_threads, bool verbose);
RcppExport SEXP _gwmvt_gwpca_cpp(SEXP dataSEXP, SEXP coordsSEXP, SEXP bandwidthSEXP, SEXP methodSEXP, SEXP use_correlationSEXP, SEXP kSEXP, SEXP detect_outliersSEXP, SEXP outlier_thresholdSEXP, SEXP trim_propSEXP, SEXP h_fractionSEXP, SEXP lof_kSEXP, SEXP bacon_alphaSEXP, SEXP depth_typeSEXP, SEXP robpca_k_maxSEXP, SEXP parallelSEXP, SEXP n_threadsSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type data(dataSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type coords(coordsSEXP);
    Rcpp::traits::input_parameter< double >::type bandwidth(bandwidthSEXP);
    Rcpp::traits::input_parameter< std::string >::type method(methodSEXP);
    Rcpp::traits::input_parameter< bool >::type use_correlation(use_correlationSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< bool >::type detect_outliers(detect_outliersSEXP);
    Rcpp::traits::input_parameter< double >::type outlier_threshold(outlier_thresholdSEXP);
    Rcpp::traits::input_parameter< double >::type trim_prop(trim_propSEXP);
    Rcpp::traits::input_parameter< double >::type h_fraction(h_fractionSEXP);
    Rcpp::traits::input_parameter< int >::type lof_k(lof_kSEXP);
    Rcpp::traits::input_parameter< double >::type bacon_alpha(bacon_alphaSEXP);
    Rcpp::traits::input_parameter< std::string >::type depth_type(depth_typeSEXP);
    Rcpp::traits::input_parameter< int >::type robpca_k_max(robpca_k_maxSEXP);
    Rcpp::traits::input_parameter< bool >::type parallel(parallelSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(gwpca_cpp(data, coords, bandwidth, method, use_correlation, k, detect_outliers, outlier_threshold, trim_prop, h_fraction, lof_k, bacon_alpha, depth_type, robpca_k_max, parallel, n_threads, verbose));
    return rcpp_result_gen;
END_RCPP
}
// detect_spatial_outliers_cpp
arma::uvec detect_spatial_outliers_cpp(const arma::mat& data, const arma::mat& coords, double bandwidth, double threshold);
RcppExport SEXP _gwmvt_detect_spatial_outliers_cpp(SEXP dataSEXP, SEXP coordsSEXP, SEXP bandwidthSEXP, SEXP thresholdSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type data(dataSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type coords(coordsSEXP);
    Rcpp::traits::input_parameter< double >::type bandwidth(bandwidthSEXP);
    Rcpp::traits::input_parameter< double >::type threshold(thresholdSEXP);
    rcpp_result_gen = Rcpp::wrap(detect_spatial_outliers_cpp(data, coords, bandwidth, threshold));
    return rcpp_result_gen;
END_RCPP
}
// adaptive_bandwidth_nn
arma::vec adaptive_bandwidth_nn(const arma::mat& coords, int k);
RcppExport SEXP _gwmvt_adaptive_bandwidth_nn(SEXP coordsSEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type coords(coordsSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    rcpp_result_gen = Rcpp::wrap(adaptive_bandwidth_nn(coords, k));
    return rcpp_result_gen;
END_RCPP
}
// morans_i
double morans_i(const arma::vec& values, const arma::mat& coords, double bandwidth);
RcppExport SEXP _gwmvt_morans_i(SEXP valuesSEXP, SEXP coordsSEXP, SEXP bandwidthSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type values(valuesSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type coords(coordsSEXP);
    Rcpp::traits::input_parameter< double >::type bandwidth(bandwidthSEXP);
    rcpp_result_gen = Rcpp::wrap(morans_i(values, coords, bandwidth));
    return rcpp_result_gen;
END_RCPP
}
// local_morans_i
arma::vec local_morans_i(const arma::vec& values, const arma::mat& coords, double bandwidth);
RcppExport SEXP _gwmvt_local_morans_i(SEXP valuesSEXP, SEXP coordsSEXP, SEXP bandwidthSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type values(valuesSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type coords(coordsSEXP);
    Rcpp::traits::input_parameter< double >::type bandwidth(bandwidthSEXP);
    rcpp_result_gen = Rcpp::wrap(local_morans_i(values, coords, bandwidth));
    return rcpp_result_gen;
END_RCPP
}
// has_openmp_support
bool has_openmp_support();
RcppExport SEXP _gwmvt_has_openmp_support() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(has_openmp_support());
    return rcpp_result_gen;
END_RCPP
}
// get_max_threads
int get_max_threads();
RcppExport SEXP _gwmvt_get_max_threads() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(get_max_threads());
    return rcpp_result_gen;
END_RCPP
}
// set_num_threads
void set_num_threads(int n);
RcppExport SEXP _gwmvt_set_num_threads(SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    set_num_threads(n);
    return R_NilValue;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_gwmvt_gwpca_cpp", (DL_FUNC) &_gwmvt_gwpca_cpp, 17},
    {"_gwmvt_detect_spatial_outliers_cpp", (DL_FUNC) &_gwmvt_detect_spatial_outliers_cpp, 4},
    {"_gwmvt_adaptive_bandwidth_nn", (DL_FUNC) &_gwmvt_adaptive_bandwidth_nn, 2},
    {"_gwmvt_morans_i", (DL_FUNC) &_gwmvt_morans_i, 3},
    {"_gwmvt_local_morans_i", (DL_FUNC) &_gwmvt_local_morans_i, 3},
    {"_gwmvt_has_openmp_support", (DL_FUNC) &_gwmvt_has_openmp_support, 0},
    {"_gwmvt_get_max_threads", (DL_FUNC) &_gwmvt_get_max_threads, 0},
    {"_gwmvt_set_num_threads", (DL_FUNC) &_gwmvt_set_num_threads, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_gwmvt(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
