# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

gwpca_cpp <- function(data, coords, bandwidth, method = "standard", use_correlation = FALSE, k = 0L, detect_outliers = TRUE, outlier_threshold = 2.5, trim_prop = 0.1, h_fraction = 0.75, lof_k = 10L, bacon_alpha = 0.05, depth_type = "mahalanobis", robpca_k_max = 10L, parallel = TRUE, n_threads = 0L, verbose = FALSE) {
    .Call(`_gwmvt_gwpca_cpp`, data, coords, bandwidth, method, use_correlation, k, detect_outliers, outlier_threshold, trim_prop, h_fraction, lof_k, bacon_alpha, depth_type, robpca_k_max, parallel, n_threads, verbose)
}

detect_spatial_outliers_cpp <- function(data, coords, bandwidth, threshold = 2.5) {
    .Call(`_gwmvt_detect_spatial_outliers_cpp`, data, coords, bandwidth, threshold)
}

adaptive_bandwidth_nn <- function(coords, k) {
    .Call(`_gwmvt_adaptive_bandwidth_nn`, coords, k)
}

morans_i <- function(values, coords, bandwidth) {
    .Call(`_gwmvt_morans_i`, values, coords, bandwidth)
}

local_morans_i <- function(values, coords, bandwidth) {
    .Call(`_gwmvt_local_morans_i`, values, coords, bandwidth)
}

has_openmp_support <- function() {
    .Call(`_gwmvt_has_openmp_support`)
}

get_max_threads <- function() {
    .Call(`_gwmvt_get_max_threads`)
}

set_num_threads <- function(n) {
    invisible(.Call(`_gwmvt_set_num_threads`, n))
}

